name: harmonic-lomb-scargle
channels:
  - conda-forge
dependencies:
  - arviz
  - matplotlib
  - numpy
  - python=3.11
  - scipy
  - lightkurve
  - ipykernel
  - ipywidgets
  - numpyro
  - pip:
    - celerite2
